{% set version = "4.0.1" %}

package:
  name: robotframework-dependencylibrary
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/r/robotframework-dependencylibrary/robotframework-dependencylibrary-{{ version }}.tar.gz
  sha256: d2382df03b9e47a27b35b417dc053fcde92c0e37d5165bb8a4e2a6b6ee7faa10

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 1

requirements:
  host:
    - pip
    - python {{ python_min }}
    - robotframework
  run:
    - python >={{ python_min }}
    - robotframework

test:
  imports:
    - DependencyLibrary
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/mentalisttraceur/robotframework-dependencylibrary
  summary: Declare dependencies between Robot Framework tests
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - bollwyvl
