{% set version = "4.0.1" %}

package:
  name: robotframework-dependencylibrary
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/r/robotframework-dependencylibrary/robotframework-dependencylibrary-{{ version }}.tar.gz
  sha256: d2382df03b9e47a27b35b417dc053fcde92c0e37d5165bb8a4e2a6b6ee7faa10

build:
  number: 1
  noarch: python
  script:
    - {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation --disable-pip-version-check

requirements:
  host:
    - pip
    - python {{ python_min }}
    - robotframework
    - setuptools
  run:
    - python >={{ python_min }}
    - robotframework

test:
  requires:
    - pip
    - python {{ python_min }}
  imports:
    - DependencyLibrary
  commands:
    - pip check

about:
  home: https://github.com/mentalisttraceur/robotframework-dependencylibrary
  summary: Declare dependencies between Robot Framework tests
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - bollwyvl
